name = "autosite-saas"
compatibility_date = "2024-05-24"
pages_build_output_dir = ".next"

# Build configuration
[build]
command = "npm run build"

# Build environment variables (for build time only)
[build.environment]
NODE_ENV = "production"
# Add placeholder values for build - real values will be in Cloudflare Pages settings
NEXT_PUBLIC_SUPABASE_URL = "https://placeholder.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "placeholder-anon-key"

# Compatibility flags for Next.js
[compatibility_flags]
nodejs_compat = true